apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - authorizationpolicy.yaml
  - pvc.yaml
  - service.yaml
  - deployment.yaml
  - virtual-service.yaml

namespace: kubeflow
