apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: custom-metric-exporter
  name: custom-metric-exporter
  namespace: utils
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: exporter
      app.kubernetes.io/name: custom-metric-exporter
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/component: exporter
        app.kubernetes.io/name: custom-metric-exporter
    spec:
      containers:
        - name: custom-metric-exporter
          image: skxogh252/custom-metric-exporter:1.16
          ports:
            - name: metrics
              containerPort: 8000
              protocol: TCP
          env:
            - name: INTERVAL
              value: "1"
            - name: DB_USER
              value: "postgres"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql
                  key: postgres-password
            - name: DB_HOST
              value: "postgresql.utils:5432"
            - name: DB
              value: "dex"
            - name: WORKSPACE_TABLE
              value: "haiqv_workspace"
            - name: MEMBER_TABLE
              value: "haiqv_member"
            - name: SA_DIR_PATH
              value: /var/run/secrets/kubernetes.io/serviceaccount
          resources:
            limits:
              cpu: 250m
              memory: 250Mi
            requests:
              cpu: 150m
              memory: 150Mi
      serviceAccountName: custom-metric-exporter-sa
