apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: longhorn-metric-exporter
  namespace: longhorn-system
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: longhorn-manager
  endpoints:
    - port: manager

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    release: kube-prometheus-stack
  name: custom-metric-exporter
  namespace: utils
spec:
  endpoints:
    - port: metrics
      interval: 1s
  selector:
    matchLabels:
      app.kubernetes.io/component: exporter
      app.kubernetes.io/name: custom-metric-exporter
