apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: gpu-metric-exporter
  name: gpu-metric-exporter
  namespace: utils
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: exporter
      app.kubernetes.io/name: gpu-metric-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/component: exporter
        app.kubernetes.io/name: gpu-metric-exporter
    spec:
      containers:
        - name: gpu-metric-exporter
          image: skxogh252/gpu-metric-exporter:1.14
          ports:
            - name: metrics
              containerPort: 8000
              protocol: TCP
          env:
            - name: INTERVAL
              value: "1"
            - name: SA_DIR_PATH
              value: /var/run/secrets/kubernetes.io/serviceaccount
          resources:
            limits:
              cpu: 250m
              memory: 250Mi
            requests:
              cpu: 150m
              memory: 150Mi
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: nvidia.com/gpu.present
                    operator: In
                    values:
                      - "true"
      serviceAccountName: custom-metric-exporter-sa
