apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-postgresql-longhorn
  namespace: utils
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn