apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - virtual-service.yaml
patchesStrategicMerge:
  - deployment-dex-patch.yaml

namespace: auth

vars:
  - name: DEX_SERVICE
    objref:
      kind: Service
      name: dex
      apiVersion: v1
    fieldref:
      fieldpath: metadata.name
  - name: DEX_NAMESPACE
    objref:
      kind: Service
      name: dex
      apiVersion: v1
    fieldref:
      fieldpath: metadata.namespace
configurations:
  - params.yaml
