{
 "title": "Cluster",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "node",
    "query": {
     "query": "label_values(kube_node_info{job=\"gpu-metrics\"}, node)"
    }
   },
   {
    "name": "workspace",
    "query": "select name\nfrom haiqv_workspace"
   },
   {
    "name": "workspace_regex",
    "query": "select concat('^', concat_ws('$|^', $workspace), '$')"
   },
   {
    "name": "namespace",
    "query": "select string_agg(t1.namespace, '|') as namespace\nfrom (\n\tselect distinct\n\tcase\n\twhen '$workspace_regex' = '^.*$' then '.*'\n\telse concat('ns-', id)\n\tend as namespace\n\tfrom haiqv_workspace\n\twhere name ~ '$workspace_regex'\n) as t1"
   },
   { "name": "buffer_factor", "query": "1.1" }
  ]
 },
 "panels": [
  { "type": "yesoreyeram-boomtheme-panel", "gridPos": { "h": 1, "w": 5, "x": 0, "y": 0 } },
  { "title": "Node Summary [ Node : $node ]", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "CPU Usage (by Node)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{node=~\"$node\", container=~\".+\"})\n OR clamp_max(absent(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{node=~\"$node\", container=~\".+\"}),0)) / sum(kube_node_status_allocatable{job=\"gpu-metrics\", node=~\"$node\", resource=\"cpu\"}) * 100"
    }
   ]
  },
  {
   "title": "GPU Usage (by Node)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(count(DCGM_FI_DEV_GPU_UTIL{kubernetes_node=~\"$node\"} > 0) OR clamp_max(absent(DCGM_FI_DEV_GPU_UTIL{kubernetes_node=~\"$node\"} > 0), 0)) / sum(kube_node_status_allocatable{job=\"gpu-metrics\", node=~\"$node\", resource=\"nvidia_com_gpu\"}) * 100"
    }
   ]
  },
  {
   "title": "Memory Usage (by Node)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(container_memory_working_set_bytes{node=~\"$node\", service=\"kube-prometheus-stack-kubelet\"})\n OR clamp_max(absent(container_memory_working_set_bytes{node=~\"$node\", service=\"kube-prometheus-stack-kubelet\"}),0)) / sum(kube_node_status_allocatable{job=\"gpu-metrics\", node=~\"$node\", resource=\"memory\"}) * 100"
    }
   ]
  },
  {
   "title": "Storage Usage (by Node)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(longhorn_node_storage_usage_bytes{node=~\"$node\"}) / sum(kube_node_status_capacity{job=\"gpu-metrics\", node=~\"$node\", resource=\"ephemeral_storage\"}) * 100"
    }
   ]
  },
  {
   "title": "CPU Quota (by Node)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "core" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{job=\"gpu-metrics\", node=~\"$node\", resource=\"cpu\"}) OR clamp_max(absent(kube_node_status_allocatable{job=\"gpu-metrics\", node=~\"$node\", resource=\"cpu\"}), 0)",
     "legendFormat": "Allocatable"
    },
    {
     "expr": "(sum(kube_pod_container_resource_requests{job=\"gpu-metrics\",node=~\"$node\", resource=\"cpu\"}) OR clamp_max(absent(kube_pod_container_resource_requests{job=\"gpu-metrics\",node=~\"$node\", resource=\"cpu\"}),0))",
     "legendFormat": "Requests"
    },
    {
     "expr": "(sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{node=~\"$node\", container=~\".+\"})\n OR clamp_max(absent(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{node=~\"$node\", container=~\".+\"}),0))",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "GPU Quota (by Node)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "unit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(kube_node_status_allocatable{job=\"gpu-metrics\", node=~\"$node\", resource=\"nvidia_com_gpu\"}) OR clamp_max(absent(kube_node_status_allocatable{job=\"gpu-metrics\", node=~\"$node\", resource=\"nvidia_com_gpu\"}),0))",
     "legendFormat": "Allocatable"
    },
    {
     "expr": "(sum(kube_pod_container_resource_requests{job=\"gpu-metrics\", node=~\"$node\", resource=\"nvidia_com_gpu\"}) OR clamp_max(absent(kube_pod_container_resource_requests{job=\"gpu-metrics\", node=~\"$node\", resource=\"nvidia_com_gpu\"}),0))",
     "legendFormat": "Requests"
    },
    {
     "expr": "count(DCGM_FI_DEV_GPU_UTIL{kubernetes_node=~\"$node\"} > 0) OR clamp_max(absent(DCGM_FI_DEV_GPU_UTIL{kubernetes_node=~\"$node\"} > 0), 0)",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Memory Quota (by Node)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{job=\"gpu-metrics\", node=~\"$node\", resource=\"memory\"}) OR clamp_max(absent(kube_node_status_allocatable{job=\"gpu-metrics\", node=~\"$node\", resource=\"memory\"}), 0)",
     "legendFormat": "Allocatable"
    },
    {
     "expr": "(sum(kube_pod_container_resource_requests{job=\"gpu-metrics\",node=~\"$node\", resource=\"memory\"}) OR clamp_max(absent(kube_pod_container_resource_requests{job=\"gpu-metrics\",node=~\"$node\", resource=\"memory\"}),0))",
     "legendFormat": "Requests"
    },
    {
     "expr": "(sum(container_memory_working_set_bytes{node=~\"$node\", service=\"kube-prometheus-stack-kubelet\"})\n OR clamp_max(absent(container_memory_working_set_bytes{node=~\"$node\", service=\"kube-prometheus-stack-kubelet\"}),0))",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Storage Quota (by Node)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity{job=\"gpu-metrics\", node=~\"$node\", resource=\"ephemeral_storage\"}) OR clamp_max(absent(kube_node_status_capacity{job=\"gpu-metrics\", node=~\"$node\", resource=\"ephemeral_storage\"}), 0)",
     "legendFormat": "Allocatable"
    },
    {
     "expr": "(sum(storage_node_disk_scheduled_bytes{node=~\"$node\"}) or clamp_max(absent(storage_node_disk_scheduled_bytes{node=~\"$node\"}),0)) + (sum(longhorn_node_storage_reservation_bytes{node=~\"$node\"}) or clamp_max(absent(longhorn_node_storage_reservation_bytes{node=~\"$node\"}), 0))",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(longhorn_node_storage_usage_bytes{node=~\"$node\"}) OR clamp_max(absent(longhorn_node_storage_usage_bytes{node=~\"$node\"}), 0)",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "GPU Summary [ Node : $node ] [ Workspace : $workspace ]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }
  },
  {
   "title": "GPU Status",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(label_replace(notebook_info * on(exported_namespace) group_left(workspace) database_workspace_info, \"namespace\", \"$1\", \"exported_namespace\", \"(.+)\")) by (namespace, workspace, notebook)"
    },
    {
     "expr": "sum(label_replace(DCGM_FI_DEV_GPU_UTIL{kubernetes_node=~\"$node\", namespace=~\"$namespace\"}, \"notebook\", \"$1\", \"container\", \"(.+)\")) by(UUID, kubernetes_node, gpu, modelName, namespace, notebook)"
    },
    {
     "expr": "sum(label_replace(DCGM_FI_DEV_MEM_COPY_UTIL{kubernetes_node=~\"$node\", namespace=~\"$namespace\"}, \"notebook\", \"$1\", \"container\", \"(.+)\")) by(UUID, kubernetes_node, gpu, modelName, namespace, notebook)"
    },
    {
     "expr": "sum(label_replace(DCGM_FI_DEV_FB_USED{kubernetes_node=~\"$node\", namespace=~\"$namespace\"} / (DCGM_FI_DEV_FB_FREE{kubernetes_node=~\"$node\", namespace=~\"$namespace\"} + DCGM_FI_DEV_FB_USED{kubernetes_node=~\"$node\", namespace=~\"$namespace\"}) * 100, \"notebook\", \"$1\", \"container\", \"(.+)\")) by(UUID, kubernetes_node, gpu, modelName, namespace, notebook)"
    },
    {
     "expr": "sum(label_replace(DCGM_FI_DEV_GPU_TEMP{kubernetes_node=~\"$node\", namespace=~\"$namespace\"}, \"notebook\", \"$1\", \"container\", \"(.+)\")) by(UUID, kubernetes_node, gpu, modelName, namespace, notebook)"
    },
    {
     "expr": "sum(label_replace(DCGM_FI_DEV_POWER_USAGE{kubernetes_node=~\"$node\", namespace=~\"$namespace\"}, \"notebook\", \"$1\", \"container\", \"(.+)\")) by(UUID, kubernetes_node, gpu, modelName, namespace, notebook)"
    }
   ]
  },
  {
   "title": "Workspace Summary [ Workspace : $workspace ]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 }
  },
  {
   "title": "Workspace Status",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(label_replace(label_replace(database_workspace_info{exported_namespace=~\"$namespace\"},\"Status\", \"1\", \"status\", \"RUNNING\"),\"Status\", \"0\", \"status\", \"WAITING\") ) by (exported_namespace, workspace, Status)"
    },
    {
     "expr": "(sum(label_replace(kube_resourcequota{job=\"gpu-metrics\", resource=\"cpu\", type=\"hard\"}, \"exported_namespace\", \"$1\", \"namespace\", \"(.+)\") and on(exported_namespace) database_workspace_info) by (exported_namespace) * 1/$buffer_factor)"
    },
    {
     "expr": "sum(label_replace(kube_resourcequota{job=\"gpu-metrics\", resource=\"requests.nvidia.com/gpu\", type=\"hard\"}, \"exported_namespace\", \"$1\", \"namespace\", \"(.+)\") and on(exported_namespace) database_workspace_info) by (exported_namespace) - sum(label_replace(kube_resourcequota{job=\"gpu-metrics\", resource=\"requests.nvidia.com/gpu\", type=\"used\"}, \"exported_namespace\", \"$1\", \"namespace\", \"(.+)\") and on(exported_namespace) database_workspace_info) by (exported_namespace)"
    },
    {
     "expr": "(sum(label_replace(kube_resourcequota{job=\"gpu-metrics\", resource=\"memory\", type=\"hard\"}, \"exported_namespace\", \"$1\", \"namespace\", \"(.+)\") and on(exported_namespace) database_workspace_info) by (exported_namespace) * 1/$buffer_factor)"
    },
    {
     "expr": "sum(label_replace(kube_resourcequota{job=\"gpu-metrics\", resource=\"requests.storage\", type=\"hard\"}, \"exported_namespace\", \"$1\", \"namespace\", \"(.+)\") and on(exported_namespace) database_workspace_info) by (exported_namespace) - sum(label_replace(kube_resourcequota{job=\"gpu-metrics\", resource=\"requests.storage\", type=\"used\"}, \"exported_namespace\", \"$1\", \"namespace\", \"(.+)\") and on(exported_namespace) database_workspace_info) by (exported_namespace)"
    },
    {
     "expr": "count(sum(notebook_info * on(exported_namespace) group_left(name) database_workspace_info) by (exported_namespace, notebook)) by (exported_namespace)"
    },
    {
     "expr": "count(label_replace(kube_persistentvolumeclaim_info{job=\"gpu-metrics\"}, \"exported_namespace\", \"$1\", \"namespace\", \"(.+)\") and on(exported_namespace) database_workspace_info) by (exported_namespace)"
    },
    {
     "expr": "-(sum(label_replace(kube_pod_container_resource_requests{job=\"gpu-metrics\", resource=\"cpu\", container!='istio-proxy'}, \"exported_namespace\", \"$1\", \"namespace\", \"(.+)\") and on (pod) label_replace(notebook_info, \"pod\", \"$1\", \"exported_pod\", \"(.+)\") and on(pod) (kube_pod_status_phase{job=\"gpu-metrics\", phase=\"Running\"} == 1)) by (exported_namespace))"
    },
    {
     "expr": "-(sum(label_replace(kube_pod_container_resource_requests{job=\"gpu-metrics\", resource=\"cpu\", container='tensorboard'}, \"exported_namespace\", \"$1\", \"namespace\", \"(.+)\") and on(pod) (kube_pod_status_phase{job=\"gpu-metrics\", phase=\"Running\"} == 1)) by (exported_namespace))"
    },
    {
     "expr": "-(sum(label_replace(kube_pod_container_resource_requests{job=\"gpu-metrics\", resource=\"memory\", container!='istio-proxy'}, \"exported_namespace\", \"$1\", \"namespace\", \"(.+)\") and on (pod) label_replace(notebook_info, \"pod\", \"$1\", \"exported_pod\", \"(.+)\") and on(pod) (kube_pod_status_phase{job=\"gpu-metrics\", phase=\"Running\"} == 1)) by (exported_namespace))"
    },
    {
     "expr": "-(sum(label_replace(kube_pod_container_resource_requests{job=\"gpu-metrics\", resource=\"memory\", container='tensorboard'}, \"exported_namespace\", \"$1\", \"namespace\", \"(.+)\") and on(pod) (kube_pod_status_phase{job=\"gpu-metrics\", phase=\"Running\"} == 1)) by (exported_namespace))"
    }
   ]
  },
  {
   "title": "Notebook Status",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "label_replace(label_replace(label_replace((label_replace(label_replace(notebook_info{exported_namespace=~\"$namespace\"}, \"pod\", \"$1\", \"exported_pod\", \"(.+)\"), \"namespace\", \"$1\", \"exported_namespace\", \"(.+)\") * on (namespace, pod) group_left(Status) (label_replace(label_replace(label_replace(label_replace(label_replace(kube_pod_status_phase{job=\"gpu-metrics\", namespace=~\"$namespace\"}, \"Status\", \"0\", \"phase\", \"Failed\"), \"Status\", \"1\", \"phase\", \"Running\"), \"Status\", \"2\", \"phase\", \"Pending\"), \"Status\", \"3\", \"phase\", \"Succeeded\"), \"Status\", \"4\", \"phase\", \"Unknown\") == 1)) * on(exported_namespace) group_left(name) database_workspace_info{exported_namespace=~\"$namespace\"}, \"namespace\", \"$1\", \"exported_namespace\", \"(.+)\"), \"pod\", \"$1\", \"exported_pod\", \"(.+)\"), \"workspace\", \"$1\", \"name\", \"(.+)\")"
    },
    {
     "expr": "label_replace(label_replace(label_replace(label_replace(notebook_info{exported_namespace=~\"$namespace\"}, \"pod\", \"$1\", \"exported_pod\", \"(.+)\") * on(exported_namespace) group_left(name) database_workspace_info{exported_namespace=~\"$namespace\"}, \"namespace\", \"$1\", \"exported_namespace\", \"(.+)\"), \"pod\", \"$1\", \"exported_pod\", \"(.+)\"), \"workspace\", \"$1\", \"name\", \"(.+)\")"
    },
    {
     "expr": "(sum(label_replace(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=~\"$namespace\", container=~\".+\"}, \"notebook\", \"$1\", \"container\", \"(.+)\") and on(notebook) notebook_info{exported_namespace=~\"$namespace\"}) by (namespace, notebook) / sum(label_replace(kube_pod_container_resource_limits{job=\"gpu-metrics\", namespace=~\"$namespace\", resource=\"cpu\", container=~\".+\"}, \"notebook\", \"$1\", \"container\", \"(.+)\") and on(notebook) notebook_info{exported_namespace=~\"$namespace\"}) by (namespace, notebook)) and on(namespace) label_replace(database_workspace_info, \"namespace\", \"$1\", \"exported_namespace\", \"(.+)\")"
    },
    {
     "expr": "count(label_replace(DCGM_FI_DEV_GPU_UTIL >= 0, \"notebook\", \"$1\", \"container\", \"(.+)\") and on(notebook) notebook_info{exported_namespace=~\"$namespace\"} and on (namespace) label_replace(database_workspace_info{exported_namespace=~\"$namespace\"}, \"namespace\", \"$1\", \"exported_namespace\", \"(.+)\")) by (namespace, notebook)"
    },
    {
     "expr": "count(label_replace(DCGM_FI_DEV_GPU_UTIL == 0, \"notebook\", \"$1\", \"container\", \"(.+)\") and on(notebook) notebook_info{exported_namespace=~\"$namespace\"} and on (namespace) label_replace(database_workspace_info{exported_namespace=~\"$namespace\"}, \"namespace\", \"$1\", \"exported_namespace\", \"(.+)\")) by (namespace, notebook)"
    },
    {
     "expr": "(sum(label_replace(container_memory_working_set_bytes{namespace=~\"$namespace\", service=\"kube-prometheus-stack-kubelet\"}, \"notebook\", \"$1\", \"container\", \"(.+)\") and on(notebook) notebook_info{exported_namespace=~\"$namespace\"}) by (namespace, notebook) / sum(label_replace(kube_pod_container_resource_limits{job=\"gpu-metrics\", namespace=~\"$namespace\", resource=\"memory\", container=~\".+\"}, \"notebook\", \"$1\", \"container\", \"(.+)\") and on(notebook) notebook_info{exported_namespace=~\"$namespace\"}) by (namespace, notebook)) and on(namespace) label_replace(database_workspace_info, \"namespace\", \"$1\", \"exported_namespace\", \"(.+)\")"
    },
    {
     "expr": "sum(notebook_info{persistentvolumeclaim!=\"NONE\"} and on (exported_namespace) database_workspace_info{exported_namespace=~\"$namespace\"}) by (notebook)"
    },
    {
     "expr": "sum(label_replace(database_workspace_info{exported_namespace=~\"$namespace\"} and on(exported_namespace) notebook_info{exported_namespace=~\"$namespace\"}, \"namespace\", \"$1\", \"exported_namespace\", \"(.+)\")) by (namespace, workspace)"
    }
   ]
  },
  {
   "title": "Node Details [ Node : $node ]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "Node Status",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 42 },
     "targets": [
      {
       "expr": "kube_node_info{job=\"gpu-metrics\", node=~\"$node\"}"
      },
      {
       "expr": "sum(kube_node_role{job=\"gpu-metrics\", node=~\"$node\", role=\"master\"} OR clamp_max(absent(kube_node_role{job=\"gpu-metrics\", node=~\"$node\", role=\"master\"}), 0)) by (node, role)"
      },
      {
       "expr": "sum(label_replace(label_replace(label_replace(kube_node_status_condition{job=\"gpu-metrics\", node=~\"$node\", condition=\"Ready\"}, \"Ready\", \"1\", \"status\", \"true\"), \"Ready\", \"0\", \"status\", \"false\"), \"Ready\", \"-1\", \"status\", \"unknown\") == 1) by (node, Ready)"
      },
      {
       "expr": "sum(label_replace(label_replace(label_replace(kube_node_status_condition{job=\"gpu-metrics\", node=~\"$node\", condition=\"DiskPressure\"}, \"DiskPressure\", \"1\", \"status\", \"true\"),\"DiskPressure\", \"0\", \"status\", \"false\"),\"DiskPressure\", \"-1\", \"status\", \"unknown\") == 1) by (node, DiskPressure)"
      },
      {
       "expr": "sum(label_replace(label_replace(label_replace(kube_node_status_condition{job=\"gpu-metrics\", node=~\"$node\", condition=\"MemoryPressure\"}, \"MemoryPressure\", \"1\", \"status\", \"true\"),\"MemoryPressure\", \"0\", \"status\", \"false\"),\"MemoryPressure\", \"-1\", \"status\", \"unknown\") == 1) by (node, MemoryPressure)"
      },
      {
       "expr": "sum(label_replace(label_replace(label_replace(kube_node_status_condition{job=\"gpu-metrics\", node=~\"$node\", condition=\"NetworkUnavailable\"}, \"NetworkUnavailable\", \"1\", \"status\", \"true\"), \"NetworkUnavailable\", \"0\", \"status\", \"false\"), \"NetworkUnavailable\", \"-1\", \"status\", \"unknown\") == 1) by (node, NetworkUnavailable)"
      },
      {
       "expr": "sum(label_replace(label_replace(label_replace(kube_node_status_condition{job=\"gpu-metrics\", node=~\"$node\", condition=\"PIDPressure\"}, \"PIDPressure\", \"1\", \"status\", \"true\"),\"PIDPressure\", \"0\", \"status\", \"false\"),\"PIDPressure\", \"-1\", \"status\", \"unknown\") == 1) by (node, PIDPressure)"
      },
      {
       "expr": "sum(label_replace(label_replace(storage_node_disk_condition{node=~\"$node\", condition=\"Schedulable\"}, \"Schedulable\", \"1\", \"status\", \"True\"), \"Schedulable\", \"1\", \"status\", \"False\") == 1) by (node, Schedulable)"
      }
     ]
    },
    {
     "title": "Storage Status (by Volume Replica)",
     "type": "table",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 50 },
     "targets": [
      {
       "expr": "label_replace(label_replace(label_replace(label_replace(label_replace(label_replace(storage_volume_replica_info{node=~\"$node\"} * on (diskID) group_left (node) storage_node_disk_info{node=~\"$node\"}, \"Running\", \"1\", \"running\", \"True\"), \"Running\", \"0\", \"running\", \"False\"), \"Status\", \"1\", \"pvStatus\", \"Available\"), \"Status\", \"2\", \"pvStatus\", \"Bound\"), \"Status\", \"3\", \"pvStatus\", \"Released\"), \"Status\", \"0\", \"pvStatus\", \"Fail\")"
      },
      {
       "expr": "sum(kube_persistentvolume_capacity_bytes{job=\"gpu-metrics\"} and on (persistentvolume) storage_volume_replica_info * on (diskID) group_left (node) storage_node_disk_info{node=~\"$node\"}) by (persistentvolume)"
      },
      {
       "expr": "sum(label_replace(longhorn_volume_actual_size_bytes, \"persistentvolume\", \"$1\", \"volume\", \"(.+)\")) by (persistentvolume)"
      },
      {
       "expr": "sum(label_replace(kube_persistentvolume_claim_ref{job=\"gpu-metrics\"}, \"persistentvolumeclaim\", \"$1\", \"name\", \"(.+)\") * on(claim_namespace) group_left(workspace) label_replace(database_workspace_info, \"claim_namespace\", \"$1\", \"exported_namespace\", \"(.+)\") and on (persistentvolume) storage_volume_replica_info * on (diskID) group_left (node) storage_node_disk_info{node=~\"$node\"}) by (workspace, claim_namespace, persistentvolumeclaim, persistentvolume)"
      }
     ]
    },
    {
     "title": "CPU Quotas (by Node)",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "core" } },
     "targets": [
      {
       "expr": "kube_node_status_allocatable{job=\"kube-state-metrics\", resource=\"cpu\", node=~\"$node\"}"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{job=\"kube-state-metrics\", resource=\"cpu\", node=~\"$node\"}) by(node)"
      },
      {
       "expr": "node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{node=~\"$node\", container=~\".+\"}"
      }
     ]
    },
    {
     "title": "CPU Usage (by Node)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "(sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=~\"$namespace\", node=~\"$node\", container=~\".+\"}) by (node)\n OR clamp_max(absent(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=~\"$namespace\", node=~\"$node\", container=~\".+\"}),0)) / sum(kube_node_status_allocatable{job=\"gpu-metrics\", node=~\"$node\", resource=\"cpu\"}) by (node)",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "GPU Quotas (by Node)",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "unit" } },
     "targets": [
      {
       "expr": "kube_node_status_allocatable{job=\"kube-state-metrics\", resource=\"nvidia_com_gpu\", node=~\"$node\"}"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{job=\"kube-state-metrics\", resource=\"nvidia_com_gpu\", node=~\"$node\"}) by(node)"
      },
      {
       "expr": "count(DCGM_FI_DEV_GPU_UTIL{kubernetes_node=~\"$node\"} > 0) OR clamp_max(absent(DCGM_FI_DEV_GPU_UTIL{kubernetes_node=~\"$node\"} > 0), 0)"
      }
     ]
    },
    {
     "title": "GPU Memory Usage (by GPU Unit)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "mbytes" } },
     "yaxes": [
      { "format": "mbytes" }
     ],
     "targets": [
      {
       "expr": "DCGM_FI_DEV_FB_USED{kubernetes_node=~\"$node\"}",
       "legendFormat": "{{kubernetes_node}}/{{gpu}}"
      }
     ]
    },
    {
     "title": "Memory Quotas (by Node)",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "kube_node_status_allocatable{job=\"kube-state-metrics\", resource=\"memory\", node=~\"$node\"}"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{job=\"kube-state-metrics\", resource=\"memory\", node=~\"$node\"}) by(node)"
      },
      {
       "expr": "sum(container_memory_working_set_bytes{node=~\"$node\", service=\"kube-prometheus-stack-kubelet\"}) by(node)"
      }
     ]
    },
    {
     "title": "Memory Usage (by Node)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "(sum(container_memory_working_set_bytes{node=~\"$node\", service=\"kube-prometheus-stack-kubelet\"}) by (node)\n OR clamp_max(absent(container_memory_working_set_bytes{node=~\"$node\", service=\"kube-prometheus-stack-kubelet\"}),0)) / sum(kube_node_status_allocatable{job=\"gpu-metrics\", node=~\"$node\", resource=\"memory\"}) by (node)",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Storage Quotas (by Node)",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 85 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "kube_node_status_capacity{job=\"gpu-metrics\", node=~\"$node\", resource=\"ephemeral_storage\"}"
      },
      {
       "expr": "(storage_node_disk_scheduled_bytes{node=~\"$node\"} + on (node) longhorn_node_storage_reservation_bytes{node=~\"$node\"})"
      },
      {
       "expr": "longhorn_node_storage_usage_bytes{node=~\"$node\"}"
      }
     ]
    },
    {
     "title": "Storage Usage (by Node)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 85 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(longhorn_node_storage_usage_bytes{node=~\"$node\"}) by (node) / sum(kube_node_status_capacity{job=\"gpu-metrics\", node=~\"$node\", resource=\"ephemeral_storage\"}) by (node)",
       "legendFormat": "{{node}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Workspace Details [ Workspace : $workspace ]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage (by Workspace)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=~\"$namespace\", container!~\"istio.*\", container=~\".+\"} and on(namespace) label_replace(database_workspace_info, \"namespace\", \"$1\", \"exported_namespace\", \"(.+)\"))\n OR clamp_max(absent(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=~\"$namespace\", container!~\"istio.*\",  container=~\".+\"} and on(namespace) label_replace(database_workspace_info, \"namespace\", \"$1\", \"exported_namespace\", \"(.+)\")),0)) / (sum(kube_resourcequota{job=\"gpu-metrics\", namespace=~\"$namespace\", resource=\"cpu\", type=\"hard\"} > 0 and on(namespace) label_replace(database_workspace_info, \"namespace\", \"$1\", \"exported_namespace\", \"(.+)\")) * 1/$buffer_factor) * 100"
      }
     ]
    },
    {
     "title": "GPU Usage (by Workspace)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 6, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(count(DCGM_FI_DEV_GPU_UTIL > 0 and on(namespace) label_replace(database_workspace_info{exported_namespace=~\"$namespace\"}, \"namespace\", \"$1\", \"exported_namespace\", \"(.+)\")) or clamp_max(absent(DCGM_FI_DEV_GPU_UTIL > 0 and on(namespace) label_replace(database_workspace_info{exported_namespace=~\"$namespace\"}, \"namespace\", \"$1\", \"exported_namespace\", \"(.+)\")), 0)) / sum(kube_resourcequota{job=\"gpu-metrics\", namespace=~\"$namespace\", resource=\"requests.nvidia.com/gpu\", type=\"hard\"} > 0 and on(namespace) label_replace(database_workspace_info{exported_namespace=~\"$namespace\"}, \"namespace\", \"$1\", \"exported_namespace\", \"(.+)\")) * 100"
      }
     ]
    },
    {
     "title": "Memory Usage (by Workspace)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 12, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum(container_memory_working_set_bytes{namespace=~\"$namespace\", container!~\"istio.*\", service=\"kube-prometheus-stack-kubelet\"} and on(namespace) label_replace(database_workspace_info, \"namespace\", \"$1\", \"exported_namespace\", \"(.+)\")) OR clamp_max(absent(container_memory_working_set_bytes{namespace=~\"$namespace\", container!~\"istio.*\", service=\"kube-prometheus-stack-kubelet\"} and on(namespace) label_replace(database_workspace_info, \"namespace\", \"$1\", \"exported_namespace\", \"(.+)\")),0)) / (sum(kube_resourcequota{job=\"gpu-metrics\", namespace=~\"$namespace\", resource=\"memory\", type=\"hard\"} > 0 and on(namespace) label_replace(database_workspace_info, \"namespace\", \"$1\", \"exported_namespace\", \"(.+)\")) * 1/$buffer_factor) * 100"
      }
     ]
    },
    {
     "title": "Storage Usage (by Workspace)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 18, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum(label_replace(longhorn_volume_actual_size_bytes, \"persistentvolume\", \"$1\", \"volume\", \"(.+)\") * on(persistentvolume) group_left(name, claim_namespace) (kube_persistentvolume_claim_ref{job=\"gpu-metrics\", claim_namespace=~\"$namespace\"} and on(claim_namespace) label_replace(database_workspace_info, \"claim_namespace\", \"$1\", \"exported_namespace\", \"(.+)\"))) OR clamp_max(absent(label_replace(longhorn_volume_actual_size_bytes, \"persistentvolume\", \"$1\", \"volume\", \"(.+)\") * on(persistentvolume) group_left(name, claim_namespace) (kube_persistentvolume_claim_ref{job=\"gpu-metrics\", claim_namespace=~\"$namespace\"} and on(claim_namespace) label_replace(database_workspace_info, \"claim_namespace\", \"$1\", \"exported_namespace\", \"(.+)\"))), 0)) / (sum(kube_resourcequota{job=\"gpu-metrics\", namespace=~\"$namespace\", resource=\"requests.storage\", type=\"hard\"} > 0 and on(namespace) label_replace(database_workspace_info, \"namespace\", \"$1\", \"exported_namespace\", \"(.+)\"))) * 100"
      }
     ]
    },
    {
     "title": "CPU Quota (by Workspace)",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "core" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_resourcequota{job=\"gpu-metrics\", namespace=~\"$namespace\", resource=\"cpu\", type=\"hard\"} and on(namespace) label_replace(database_workspace_info, \"namespace\", \"$1\", \"exported_namespace\", \"(.+)\")) * 1/$buffer_factor",
       "legendFormat": "Limits"
      },
      {
       "expr": "(sum(kube_pod_container_resource_requests{job=\"gpu-metrics\", namespace=~\"$namespace\", resource=\"cpu\", container!='istio-proxy'} and on (pod) label_replace(notebook_info{exported_namespace=~\"$namespace\"}, \"pod\", \"$1\", \"exported_pod\", \"(.+)\") and on(pod) (kube_pod_status_phase{job=\"gpu-metrics\", namespace=~\"$namespace\",phase=\"Running\"} == 1)) or clamp_max(absent(kube_pod_container_resource_requests{job=\"gpu-metrics\", namespace=~\"$namespace\", resource=\"cpu\", container!='istio-proxy'} and on (pod) label_replace(notebook_info{exported_namespace=~\"$namespace\"}, \"pod\", \"$1\", \"exported_pod\", \"(.+)\") and on(pod) (kube_pod_status_phase{job=\"gpu-metrics\", namespace=~\"$namespace\",phase=\"Running\"} == 1)), 0))\n+\n(sum(kube_pod_container_resource_requests{job=\"gpu-metrics\", namespace=~\"$namespace\", resource=\"cpu\", container='tensorboard'} and on(pod) (kube_pod_status_phase{job=\"gpu-metrics\", namespace=~\"$namespace\",phase=\"Running\"} == 1)) or clamp_max(absent(kube_pod_container_resource_requests{job=\"gpu-metrics\", namespace=~\"$namespace\", resource=\"cpu\", container='tensorboard'} and on(pod) (kube_pod_status_phase{job=\"gpu-metrics\", namespace=~\"$namespace\",phase=\"Running\"} == 1)), 0))",
       "legendFormat": "Requests"
      },
      {
       "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=~\"$namespace\", container!~\"istio.*\", container=~\".+\"} and on(namespace) label_replace(database_workspace_info, \"namespace\", \"$1\", \"exported_namespace\", \"(.+)\")) OR clamp_max(absent(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=~\"$namespace\", container!~\"istio.*\", container=~\".+\"} and on(namespace) label_replace(database_workspace_info, \"namespace\", \"$1\", \"exported_namespace\", \"(.+)\")), 0)",
       "legendFormat": "Used"
      }
     ]
    },
    {
     "title": "GPU Quota (by Workspace)",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "unit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_resourcequota{job=\"gpu-metrics\", namespace=~\"$namespace\", resource=\"requests.nvidia.com/gpu\", type=\"hard\"} and on(namespace) label_replace(database_workspace_info, \"namespace\", \"$1\", \"exported_namespace\", \"(.+)\"))",
       "legendFormat": "Limits"
      },
      {
       "expr": "sum(kube_resourcequota{job=\"gpu-metrics\", namespace=~\"$namespace\", resource=\"requests.nvidia.com/gpu\", type=\"used\"} and on(namespace) label_replace(database_workspace_info, \"namespace\", \"$1\", \"exported_namespace\", \"(.+)\"))",
       "legendFormat": "Requests"
      },
      {
       "expr": "count(DCGM_FI_DEV_GPU_UTIL > 0 and on(namespace) label_replace(database_workspace_info{exported_namespace=~\"$namespace\"}, \"namespace\", \"$1\", \"exported_namespace\", \"(.+)\")) or clamp_max(absent(DCGM_FI_DEV_GPU_UTIL > 0 and on(namespace) label_replace(database_workspace_info{exported_namespace=~\"$namespace\"}, \"namespace\", \"$1\", \"exported_namespace\", \"(.+)\")), 0)",
       "legendFormat": "Used"
      }
     ]
    },
    {
     "title": "Memory Quota (by Workspace)",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_resourcequota{job=\"gpu-metrics\", namespace=~\"$namespace\", resource=\"memory\", type=\"hard\"} and on(namespace) label_replace(database_workspace_info, \"namespace\", \"$1\", \"exported_namespace\", \"(.+)\")) * 1/$buffer_factor",
       "legendFormat": "Limits"
      },
      {
       "expr": "(sum(kube_pod_container_resource_requests{job=\"gpu-metrics\", namespace=~\"$namespace\", resource=\"memory\", container!='istio-proxy'} and on (pod) label_replace(notebook_info{exported_namespace=~\"$namespace\"}, \"pod\", \"$1\", \"exported_pod\", \"(.+)\") and on(pod) (kube_pod_status_phase{job=\"gpu-metrics\", namespace=~\"$namespace\",phase=\"Running\"} == 1)) or clamp_max(absent(kube_pod_container_resource_requests{job=\"gpu-metrics\", namespace=~\"$namespace\", resource=\"memory\", container!='istio-proxy'} and on (pod) label_replace(notebook_info{exported_namespace=~\"$namespace\"}, \"pod\", \"$1\", \"exported_pod\", \"(.+)\") and on(pod) (kube_pod_status_phase{job=\"gpu-metrics\", namespace=~\"$namespace\",phase=\"Running\"} == 1)), 0))\n+\n(sum(kube_pod_container_resource_requests{job=\"gpu-metrics\", namespace=~\"$namespace\", resource=\"memory\", container='tensorboard'} and on(pod) (kube_pod_status_phase{job=\"gpu-metrics\", namespace=~\"$namespace\",phase=\"Running\"} == 1)) or clamp_max(absent(kube_pod_container_resource_requests{job=\"gpu-metrics\", namespace=~\"$namespace\", resource=\"memory\", container='tensorboard'} and on(pod) (kube_pod_status_phase{job=\"gpu-metrics\", namespace=~\"$namespace\",phase=\"Running\"} == 1)), 0))",
       "legendFormat": "Requests"
      },
      {
       "expr": "sum(container_memory_working_set_bytes{namespace=~\"$namespace\", container!~\"istio.*\", service=\"kube-prometheus-stack-kubelet\"} and on(namespace) label_replace(database_workspace_info, \"namespace\", \"$1\", \"exported_namespace\", \"(.+)\")) OR clamp_max(absent(container_memory_working_set_bytes{namespace=~\"$namespace\", container!~\"istio.*\", service=\"kube-prometheus-stack-kubelet\"} and on(namespace) label_replace(database_workspace_info, \"namespace\", \"$1\", \"exported_namespace\", \"(.+)\")), 0)",
       "legendFormat": "Used"
      }
     ]
    },
    {
     "title": "Storage Quota (by Workspace)",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_resourcequota{job=\"gpu-metrics\", namespace=~\"$namespace\", resource=\"requests.storage\", type=\"hard\"} and on(namespace) label_replace(database_workspace_info, \"namespace\", \"$1\", \"exported_namespace\", \"(.+)\")) OR clamp_max(absent(kube_resourcequota{job=\"gpu-metrics\", namespace=~\"$namespace\", resource=\"requests.storage\", type=\"hard\"} and on(namespace) label_replace(database_workspace_info, \"namespace\", \"$1\", \"exported_namespace\", \"(.+)\")), 0)",
       "legendFormat": "Limits"
      },
      {
       "expr": "sum(kube_resourcequota{job=\"gpu-metrics\", namespace=~\"$namespace\", resource=\"requests.storage\", type=\"used\"} and on(namespace) label_replace(database_workspace_info, \"namespace\", \"$1\", \"exported_namespace\", \"(.+)\")) OR clamp_max(absent(kube_resourcequota{job=\"gpu-metrics\", namespace=~\"$namespace\", resource=\"requests.storage\", type=\"used\"} and on(namespace) label_replace(database_workspace_info, \"namespace\", \"$1\", \"exported_namespace\", \"(.+)\")), 0)",
       "legendFormat": "Requests"
      },
      {
       "expr": "sum(label_replace(longhorn_volume_actual_size_bytes, \"persistentvolume\", \"$1\", \"volume\", \"(.+)\") * on(persistentvolume) group_left(name, claim_namespace) (kube_persistentvolume_claim_ref{job=\"gpu-metrics\", claim_namespace=~\"$namespace\"} and on(claim_namespace) label_replace(database_workspace_info, \"claim_namespace\", \"$1\", \"exported_namespace\", \"(.+)\"))) OR clamp_max(absent(label_replace(longhorn_volume_actual_size_bytes, \"persistentvolume\", \"$1\", \"volume\", \"(.+)\") * on(persistentvolume) group_left(name, claim_namespace) (kube_persistentvolume_claim_ref{job=\"gpu-metrics\", claim_namespace=~\"$namespace\"} and on(claim_namespace) label_replace(database_workspace_info, \"claim_namespace\", \"$1\", \"exported_namespace\", \"(.+)\"))), 0)",
       "legendFormat": "Used"
      }
     ]
    },
    {
     "title": "Volume Status (by Workspace)",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 51 },
     "targets": [
      {
       "expr": "label_replace(label_replace(label_replace(label_replace(label_replace(label_replace(label_replace(label_replace(storage_volume_info, \"State\", \"1\", \"state\", \"attached\"), \"State\", \"0\", \"state\", \"detached\"), \"Status\", \"1\", \"pvStatus\", \"Available\"), \"Status\", \"2\", \"pvStatus\", \"Bound\"), \"Status\", \"3\", \"pvStatus\", \"Released\"), \"Status\", \"0\", \"pvStatus\", \"Fail\"), \"Robustness\", \"1\", \"robustness\", \"healthy\"), \"Robustness\", \"0\", \"robustness\", \"unknown\") * on (persistentvolume) group_left (claim_namespace) label_replace(kube_persistentvolume_claim_ref{job=\"gpu-metrics\", claim_namespace=~\"$namespace\"}, \"persistentvolumeclaim\", \"$1\", \"name\", \"(.+)\") * on (claim_namespace) group_left (workspace) label_replace(database_workspace_info{exported_namespace=~\"$namespace\"}, \"claim_namespace\", \"$1\", \"exported_namespace\", \"(.+)\")"
      },
      {
       "expr": "sum(label_replace(label_replace(longhorn_volume_actual_size_bytes, \"persistentvolume\", \"$1\", \"volume\", \"(.+)\") * on(persistentvolume) group_left(name, claim_namespace) kube_persistentvolume_claim_ref{job=\"gpu-metrics\", claim_namespace=~\"$namespace\"} and on (claim_namespace) label_replace(database_workspace_info{exported_namespace=~\"$namespace\"}, \"claim_namespace\", \"$1\", \"exported_namespace\", \"(.+)\") and on (persistentvolume) kube_persistentvolume_info{job=\"gpu-metrics\", storageclass=~\"longhorn|longhorn-static\"}, \"persistentvolumeclaim\", \"$1\", \"name\", \"(.+)\") * on(claim_namespace) group_left(workspace) label_replace(database_workspace_info{exported_namespace=~\"$namespace\"}, \"claim_namespace\", \"$1\", \"exported_namespace\", \"(.+)\")) by (workspace, persistentvolume, persistentvolumeclaim)\n/\nsum(kube_persistentvolume_capacity_bytes{job=\"gpu-metrics\"} * on (persistentvolume) group_left(namespace, persistentvolumeclaim) label_replace(kube_persistentvolumeclaim_info{job=\"gpu-metrics\", namespace=~\"$namespace\"}, \"persistentvolume\", \"$1\", \"volumename\", \"(.+)\") * on(namespace) group_left(workspace) label_replace(database_workspace_info{exported_namespace=~\"$namespace\"}, \"namespace\", \"$1\", \"exported_namespace\", \"(.+)\")) by (workspace, persistentvolume, persistentvolumeclaim)"
      }
     ]
    },
    {
     "title": "CPU Quotas (by Notebook)",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "core" } },
     "targets": [
      {
       "expr": "label_replace(label_replace(notebook_info{exported_namespace=~\"$namespace\"}, \"pod\", \"$1\", \"exported_pod\", \"(.+)\") * on(exported_namespace) group_left(workspace) database_workspace_info{exported_namespace=~\"$namespace\"}, \"namespace\", \"$1\", \"exported_namespace\", \"(.+)\")"
      },
      {
       "expr": "kube_pod_container_resource_limits{job=\"gpu-metrics\", namespace=~\"$namespace\", resource=\"cpu\", container=~\".+\"} and on(container) label_replace(notebook_info, \"container\", \"$1\", \"notebook\", \"(.+)\")"
      },
      {
       "expr": "kube_pod_container_resource_requests{job=\"gpu-metrics\", namespace=~\"$namespace\", resource=\"cpu\", container=~\".+\"} and on(container) label_replace(notebook_info, \"container\", \"$1\", \"notebook\", \"(.+)\")"
      },
      {
       "expr": "node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=~\"$namespace\", container=~\".+\"} and on(container) label_replace(notebook_info{exported_namespace=~\"$namespace\"}, \"container\", \"$1\", \"notebook\", \"(.+)\")"
      }
     ]
    },
    {
     "title": "CPU Usage (by Notebook)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "((sum(label_replace(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=~\"$namespace\", container=~\".+\"}, \"notebook\", \"$1\", \"container\", \"(.+)\") and on(notebook) notebook_info{exported_namespace=~\"$namespace\"}) by (namespace, notebook) / sum(label_replace(kube_pod_container_resource_limits{job=\"gpu-metrics\", namespace=~\"$namespace\", resource=\"cpu\", container=~\".+\"}, \"notebook\", \"$1\", \"container\", \"(.+)\") and on(notebook) notebook_info{exported_namespace=~\"$namespace\"}) by (namespace, notebook)) and on(namespace) label_replace(database_workspace_info, \"namespace\", \"$1\", \"exported_namespace\", \"(.+)\")) * on (namespace) group_left(workspace) label_replace(database_workspace_info, \"namespace\", \"$1\", \"exported_namespace\", \"(.+)\")",
       "legendFormat": "{{notebook}}"
      }
     ]
    },
    {
     "title": "GPU Quota (by Notebook)",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "unit" } },
     "targets": [
      {
       "expr": "label_replace(label_replace(notebook_info{exported_namespace=~\"$namespace\"}, \"pod\", \"$1\", \"exported_pod\", \"(.+)\") * on(exported_namespace) group_left(workspace) database_workspace_info{exported_namespace=~\"$namespace\"}, \"namespace\", \"$1\", \"exported_namespace\", \"(.+)\")"
      },
      {
       "expr": "sum(label_replace(kube_pod_container_resource_limits{job=\"gpu-metrics\", namespace=~\"$namespace\", resource=\"nvidia_com_gpu\", container=~\".+\"}, \"notebook\", \"$1\", \"container\", \"(.+)\") and on(notebook) notebook_info{exported_namespace=~\"$namespace\"} and on (namespace) label_replace(database_workspace_info{exported_namespace=~\"$namespace\"}, \"namespace\", \"$1\", \"exported_namespace\", \"(.+)\")) by (namespace, notebook)"
      },
      {
       "expr": "sum(label_replace(kube_pod_container_resource_requests{job=\"gpu-metrics\", namespace=~\"$namespace\", resource=\"nvidia_com_gpu\", container=~\".+\"}, \"notebook\", \"$1\", \"container\", \"(.+)\") and on(notebook) notebook_info{exported_namespace=~\"$namespace\"} and on (namespace) label_replace(database_workspace_info{exported_namespace=~\"$namespace\"}, \"namespace\", \"$1\", \"exported_namespace\", \"(.+)\")) by (namespace, notebook)"
      },
      {
       "expr": "count(label_replace(DCGM_FI_DEV_GPU_UTIL >= 0, \"notebook\", \"$1\", \"container\", \"(.+)\") and on(notebook) notebook_info{exported_namespace=~\"$namespace\"} and on (namespace) label_replace(database_workspace_info{exported_namespace=~\"$namespace\"}, \"namespace\", \"$1\", \"exported_namespace\", \"(.+)\")) by (namespace, notebook)"
      },
      {
       "expr": "count(label_replace(DCGM_FI_DEV_GPU_UTIL == 0, \"notebook\", \"$1\", \"container\", \"(.+)\") and on(notebook) notebook_info{exported_namespace=~\"$namespace\"} and on (namespace) label_replace(database_workspace_info{exported_namespace=~\"$namespace\"}, \"namespace\", \"$1\", \"exported_namespace\", \"(.+)\")) by (namespace, notebook) or clamp_max(absent(count(label_replace(DCGM_FI_DEV_GPU_UTIL == 0, \"notebook\", \"$1\", \"container\", \"(.+)\") and on(notebook) notebook_info{exported_namespace=~\"$namespace\"} and on (namespace) label_replace(database_workspace_info{exported_namespace=~\"$namespace\"}, \"namespace\", \"$1\", \"exported_namespace\", \"(.+)\")) by (namespace, notebook)), 0)"
      }
     ]
    },
    {
     "title": "GPU Memory Usage (by Notebook)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "mbytes" } },
     "yaxes": [
      { "format": "mbytes" }
     ],
     "targets": [
      {
       "expr": "label_replace(DCGM_FI_DEV_FB_USED{namespace=~\"$namespace\"}, \"notebook\", \"$1\", \"container\", \"(.+)\") and on (notebook) (notebook_info{exported_namespace=~\"$namespace\"} and on (exported_namespace) database_workspace_info{exported_namespace=~\"$namespace\"})",
       "legendFormat": "{{notebook}}/{{kubernetes_node}}/{{gpu}}"
      }
     ]
    },
    {
     "title": "Memory Quotas (by Notebook)",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "label_replace(label_replace(notebook_info{exported_namespace=~\"$namespace\"}, \"pod\", \"$1\", \"exported_pod\", \"(.+)\") * on(exported_namespace) group_left(workspace) database_workspace_info{exported_namespace=~\"$namespace\"}, \"namespace\", \"$1\", \"exported_namespace\", \"(.+)\")"
      },
      {
       "expr": "kube_pod_container_resource_limits{job=\"gpu-metrics\", namespace=~\"$namespace\", resource=\"memory\", container=~\".+\"} and on(container) label_replace(notebook_info, \"container\", \"$1\", \"notebook\", \"(.+)\")"
      },
      {
       "expr": "kube_pod_container_resource_requests{job=\"gpu-metrics\", namespace=~\"$namespace\", resource=\"memory\", container=~\".+\"} and on(container) label_replace(notebook_info, \"container\", \"$1\", \"notebook\", \"(.+)\")"
      },
      {
       "expr": "container_memory_working_set_bytes{namespace=~\"$namespace\", service=\"kube-prometheus-stack-kubelet\"} and on(container) label_replace(notebook_info{exported_namespace=~\"$namespace\"}, \"container\", \"$1\", \"notebook\", \"(.+)\")"
      }
     ]
    },
    {
     "title": "Memory Usage (by Notebook)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "((sum(label_replace(container_memory_working_set_bytes{namespace=~\"$namespace\", container=~\".+\", service=\"kube-prometheus-stack-kubelet\"}, \"notebook\", \"$1\", \"container\", \"(.+)\") and on(notebook) notebook_info{exported_namespace=~\"$namespace\"}) by (namespace, notebook) / sum(label_replace(kube_pod_container_resource_limits{job=\"gpu-metrics\", namespace=~\"$namespace\", resource=\"memory\", container=~\".+\"}, \"notebook\", \"$1\", \"container\", \"(.+)\") and on(notebook) notebook_info{exported_namespace=~\"$namespace\"}) by (namespace, notebook)) and on(namespace) label_replace(database_workspace_info, \"namespace\", \"$1\", \"exported_namespace\", \"(.+)\")) * on (namespace) group_left(workspace) label_replace(database_workspace_info, \"namespace\", \"$1\", \"exported_namespace\", \"(.+)\")",
       "legendFormat": "{{notebook}}"
      }
     ]
    },
    {
     "title": "Storage Quotas (by Volume)",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 85 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(label_replace(label_replace(notebook_info{exported_namespace=~\"$namespace\"}, \"pod\", \"$1\", \"exported_pod\", \"(.+)\") * on(exported_namespace) group_left(workspace) database_workspace_info{exported_namespace=~\"$namespace\"}, \"namespace\", \"$1\", \"exported_namespace\", \"(.+)\")) by (namespace, workspace, notebook, persistentvolumeclaim)"
      },
      {
       "expr": "sum(kube_persistentvolume_capacity_bytes{job=\"gpu-metrics\"} * on (persistentvolume) group_left(namespace, persistentvolumeclaim) label_replace(kube_persistentvolumeclaim_info{job=\"gpu-metrics\", namespace=~\"$namespace\"}, \"persistentvolume\", \"$1\", \"volumename\", \"(.+)\") * on(namespace) group_left(workspace) label_replace(database_workspace_info{exported_namespace=~\"$namespace\"}, \"namespace\", \"$1\", \"exported_namespace\", \"(.+)\")) by (workspace, namespace, persistentvolume, persistentvolumeclaim)"
      },
      {
       "expr": "sum(label_replace(label_replace(longhorn_volume_actual_size_bytes, \"persistentvolume\", \"$1\", \"volume\", \"(.+)\") * on(persistentvolume) group_left(name, claim_namespace) kube_persistentvolume_claim_ref{job=\"gpu-metrics\", claim_namespace=~\"$namespace\"} and on (claim_namespace) label_replace(database_workspace_info{exported_namespace=~\"$namespace\"}, \"claim_namespace\", \"$1\", \"exported_namespace\", \"(.+)\") and on (persistentvolume) kube_persistentvolume_info{job=\"gpu-metrics\", storageclass=~\"longhorn|longhorn-static\"}, \"persistentvolumeclaim\", \"$1\", \"name\", \"(.+)\") * on(claim_namespace) group_left(workspace) label_replace(database_workspace_info{exported_namespace=~\"$namespace\"}, \"claim_namespace\", \"$1\", \"exported_namespace\", \"(.+)\")) by (workspace, persistentvolumeclaim)"
      }
     ]
    },
    {
     "title": "Storage Usage (by Volume)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 85 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "label_replace(longhorn_volume_actual_size_bytes / longhorn_volume_capacity_bytes * 100, \"persistentvolume\", \"$1\", \"volume\", \"(.+)\") * on(persistentvolume) group_left(name, claim_namespace) (kube_persistentvolume_claim_ref{job=\"gpu-metrics\", claim_namespace=~\"$namespace\"} and on(claim_namespace) label_replace(database_workspace_info, \"claim_namespace\", \"$1\", \"exported_namespace\", \"(.+)\"))",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  }
 ]
}
{
 "title": "Modal",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "buffer_factor", "query": "1.1" },
   { "name": "longhorn_replica_count", "query": "2" }
  ]
 },
 "panels": [
  {
   "type": "table",
   "gridPos": { "h": 3, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(sum(kube_node_status_allocatable{job=\"gpu-metrics\", resource=\"cpu\"}) - sum(kube_resourcequota{job=\"gpu-metrics\", namespace=~\"ns-.*\", resource=\"cpu\", type=\"hard\"} or clamp_max(absent(kube_resourcequota{job=\"gpu-metrics\", namespace=~\"ns-.*\", resource=\"cpu\", type=\"hard\"}), 0))) * 1/$buffer_factor"
    },
    {
     "expr": "(sum(kube_node_status_allocatable{job=\"gpu-metrics\", resource=\"nvidia_com_gpu\"}) or clamp_max(absent(kube_node_status_allocatable{job=\"gpu-metrics\", resource=\"nvidia_com_gpu\"}), 0)) - scalar(sum(kube_resourcequota{job=\"gpu-metrics\", resource=\"requests.nvidia.com/gpu\", type=\"hard\"}) or clamp_max(absent(kube_resourcequota{job=\"gpu-metrics\", resource=\"requests.nvidia.com/gpu\", type=\"hard\"}), 0))"
    },
    {
     "expr": "(sum(kube_node_status_allocatable{job=\"gpu-metrics\", resource=\"memory\"}) - sum(kube_resourcequota{job=\"gpu-metrics\", namespace=~\"ns-.*\", resource=\"memory\", type=\"hard\"} or clamp_max(absent(kube_resourcequota{job=\"gpu-metrics\", namespace=~\"ns-.*\", resource=\"memory\", type=\"hard\"}), 0))) * 1/$buffer_factor"
    },
    {
     "expr": "((sum(kube_node_status_capacity{job=\"gpu-metrics\", resource=\"ephemeral_storage\"}) OR clamp_max(absent(kube_node_status_capacity{job=\"gpu-metrics\", resource=\"ephemeral_storage\"}), 0))\n- \n((sum(storage_node_disk_scheduled_bytes) or clamp_max(absent(storage_node_disk_scheduled_bytes),0)) + (sum(longhorn_node_storage_reservation_bytes) or clamp_max(absent(longhorn_node_storage_reservation_bytes), 0)))) / $longhorn_replica_count"
    }
   ]
  }
 ]
}
{
 "title": "Notebook",
 "time": { "from": "now-10m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": "select concat('ns-', id) as namespace\nfrom haiqv_workspace"
   },
   { "name": "buffer_factor", "query": "1.1" },
   {
    "name": "notebook",
    "query": {
     "query": "label_values(notebook_info{exported_namespace=~\"$namespace\"}, notebook)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "table",
   "gridPos": { "h": 2, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=~\"$namespace\", container=~\"$notebook\"}) by (namespace, container)\n/\nsum(kube_pod_container_resource_limits{job=\"gpu-metrics\", namespace=~\"$namespace\", resource=\"cpu\", container=~\"$notebook\"}) by (namespace, container)"
    },
    {
     "expr": "((count(DCGM_FI_DEV_GPU_UTIL{namespace=~\"$namespace\", container=~\"$notebook\"} >= 0) by (namespace, container) or clamp_max(absent(_{namespace=\"$namespace\", container=\"$notebook\"}), 0))\n-\n(count(DCGM_FI_DEV_GPU_UTIL{namespace=~\"$namespace\", container=~\"$notebook\"} == 0) by (namespace, container) or clamp_max(absent(_{namespace=\"$namespace\", container=\"$notebook\"}), 0)))\n/\nsum(kube_pod_container_resource_limits{job=\"gpu-metrics\", namespace=~\"$namespace\", resource=\"nvidia_com_gpu\", container=~\"$notebook\"} > 0) by (namespace, container)  or clamp_max(absent(_{namespace=\"$namespace\", container=\"$notebook\"}), -1)"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=~\"$namespace\", service=\"kube-prometheus-stack-kubelet\", container=~\"$notebook\"}) by (namespace, container)\n/\nsum(kube_pod_container_resource_limits{job=\"gpu-metrics\", namespace=~\"$namespace\", resource=\"memory\", container=~\"$notebook\"}) by (namespace, container)"
    },
    {
     "expr": "clamp_max(absent(_{namespace=\"$namespace\", container=\"$notebook\", value_1=\"CPU\", value_2=\"GPU\", value_3=\"MEM\"}), 0)"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 2, "w": 9, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "(sum(kube_resourcequota{job=\"gpu-metrics\", namespace=~\"$namespace\", resource=\"cpu\", type=\"hard\"}) * 1/$buffer_factor)\n-\n((sum(kube_pod_container_resource_requests{job=\"gpu-metrics\", namespace=~\"$namespace\", resource=\"cpu\", container!='istio-proxy'} and on (pod) label_replace(notebook_info{exported_namespace=~\"$namespace\"}, \"pod\", \"$1\", \"exported_pod\", \"(.+)\") and on(pod) (kube_pod_status_phase{job=\"gpu-metrics\", namespace=~\"$namespace\",phase=\"Running\"} == 1)) or clamp_max(absent(kube_pod_container_resource_requests{job=\"gpu-metrics\", namespace=~\"$namespace\", resource=\"cpu\", container!='istio-proxy'} and on (pod) label_replace(notebook_info{exported_namespace=~\"$namespace\"}, \"pod\", \"$1\", \"exported_pod\", \"(.+)\") and on(pod) (kube_pod_status_phase{job=\"gpu-metrics\", namespace=~\"$namespace\",phase=\"Running\"} == 1)), 0))\n+\n(sum(kube_pod_container_resource_requests{job=\"gpu-metrics\", namespace=~\"$namespace\", resource=\"cpu\", container='tensorboard'} and on(pod) (kube_pod_status_phase{job=\"gpu-metrics\", namespace=~\"$namespace\",phase=\"Running\"} == 1)) or clamp_max(absent(kube_pod_container_resource_requests{job=\"gpu-metrics\", namespace=~\"$namespace\", resource=\"cpu\", container='tensorboard'} and on(pod) (kube_pod_status_phase{job=\"gpu-metrics\", namespace=~\"$namespace\",phase=\"Running\"} == 1)), 0)))"
    },
    {
     "expr": "sum(kube_resourcequota{job=\"gpu-metrics\", namespace=\"$namespace\", resource=\"requests.nvidia.com/gpu\", type=\"hard\"}) - sum(kube_resourcequota{job=\"gpu-metrics\", namespace=\"$namespace\", resource=\"requests.nvidia.com/gpu\", type=\"used\"})"
    },
    {
     "expr": "(sum(kube_resourcequota{job=\"gpu-metrics\", namespace=~\"$namespace\", resource=\"memory\", type=\"hard\"}) * 1/$buffer_factor)\n-\n((sum(kube_pod_container_resource_requests{job=\"gpu-metrics\", namespace=~\"$namespace\", resource=\"memory\", container!='istio-proxy'} and on (pod) label_replace(notebook_info{exported_namespace=~\"$namespace\"}, \"pod\", \"$1\", \"exported_pod\", \"(.+)\") and on(pod) (kube_pod_status_phase{job=\"gpu-metrics\", namespace=~\"$namespace\",phase=\"Running\"} == 1)) or clamp_max(absent(kube_pod_container_resource_requests{job=\"gpu-metrics\", namespace=~\"$namespace\", resource=\"memory\", container!='istio-proxy'} and on (pod) label_replace(notebook_info{exported_namespace=~\"$namespace\"}, \"pod\", \"$1\", \"exported_pod\", \"(.+)\") and on(pod) (kube_pod_status_phase{job=\"gpu-metrics\", namespace=~\"$namespace\",phase=\"Running\"} == 1)), 0))\n+\n(sum(kube_pod_container_resource_requests{job=\"gpu-metrics\", namespace=~\"$namespace\", resource=\"memory\", container='tensorboard'} and on(pod) (kube_pod_status_phase{job=\"gpu-metrics\", namespace=~\"$namespace\",phase=\"Running\"} == 1)) or clamp_max(absent(kube_pod_container_resource_requests{job=\"gpu-metrics\", namespace=~\"$namespace\", resource=\"memory\", container='tensorboard'} and on(pod) (kube_pod_status_phase{job=\"gpu-metrics\", namespace=~\"$namespace\",phase=\"Running\"} == 1)), 0)))"
    },
    {
     "expr": "sum(kube_resourcequota{job=\"gpu-metrics\", namespace=\"$namespace\", resource=\"requests.storage\", type=\"hard\"}) - sum(kube_resourcequota{job=\"gpu-metrics\", namespace=\"$namespace\", resource=\"requests.storage\", type=\"used\"})"
    }
   ]
  }
 ]
}
{
 "title": "Workspace",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "node",
    "query": {
     "query": "label_values(kube_node_info{job=\"gpu-metrics\"}, node)"
    }
   },
   {
    "name": "workspace",
    "query": "select name\nfrom haiqv_workspace"
   },
   {
    "name": "workspace_regex",
    "query": "select concat('^', concat_ws('$|^', $workspace), '$')"
   },
   {
    "name": "namespace",
    "query": "select string_agg(t1.namespace, '|') as namespace\nfrom (\n\tselect distinct\n\tcase\n\twhen '$workspace_regex' = '^.*$' then '.*'\n\telse concat('ns-', id)\n\tend as namespace\n\tfrom haiqv_workspace\n\twhere name ~ '$workspace_regex'\n) as t1"
   },
   { "name": "buffer_factor", "query": "1.1" }
  ]
 },
 "panels": [
  { "type": "yesoreyeram-boomtheme-panel", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=~\"$namespace\", container!~\"istio.*\", container=~\".+\"} OR clamp_max(absent(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=~\"$namespace\", container!~\"istio.*\", container=~\".+\"}), 0))\n/\n(sum(kube_resourcequota{job=\"gpu-metrics\", namespace=~\"$namespace\", resource=\"cpu\", type=\"hard\"}) * 1/$buffer_factor) * 100"
    }
   ]
  },
  {
   "title": "GPU Usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scalar(count(DCGM_FI_DEV_GPU_UTIL{namespace=~\"$namespace\"} > 0) or clamp_max(absent(DCGM_FI_DEV_GPU_UTIL{namespace=~\"$namespace\"} > 0), 0)) / scalar(sum(kube_resourcequota{job=\"gpu-metrics\", namespace=~\"$namespace\", resource=\"requests.nvidia.com/gpu\", type=\"hard\"} > 0)) * 100"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=~\"$namespace\", container!~\"istio.*\", service=\"kube-prometheus-stack-kubelet\"} OR clamp_max(absent(container_memory_working_set_bytes{namespace=~\"$namespace\", container!~\"istio.*\", service=\"kube-prometheus-stack-kubelet\"}), 0))\n/\n(sum(kube_resourcequota{job=\"gpu-metrics\", namespace=~\"$namespace\", resource=\"memory\", type=\"hard\"} > 0) * 1/$buffer_factor) * 100"
    }
   ]
  },
  {
   "title": "Storage Usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(label_replace(longhorn_volume_actual_size_bytes, \"persistentvolume\", \"$1\", \"volume\", \"(.+)\") * on(persistentvolume) group_left(name, claim_namespace) (kube_persistentvolume_claim_ref{job=\"gpu-metrics\", claim_namespace=~\"$namespace\"} and on(claim_namespace) label_replace(database_workspace_info, \"claim_namespace\", \"$1\", \"exported_namespace\", \"(.+)\"))) OR clamp_max(absent(label_replace(longhorn_volume_actual_size_bytes, \"persistentvolume\", \"$1\", \"volume\", \"(.+)\") * on(persistentvolume) group_left(name, claim_namespace) (kube_persistentvolume_claim_ref{job=\"gpu-metrics\", claim_namespace=~\"$namespace\"} and on(claim_namespace) label_replace(database_workspace_info, \"claim_namespace\", \"$1\", \"exported_namespace\", \"(.+)\"))), 0)) / (sum(kube_resourcequota{job=\"gpu-metrics\", namespace=~\"$namespace\", resource=\"requests.storage\", type=\"hard\"} > 0)) * 100"
    }
   ]
  },
  {
   "title": "CPU Quota",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "core" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_resourcequota{job=\"gpu-metrics\", namespace=~\"$namespace\", resource=\"cpu\", type=\"hard\"}) * 1/$buffer_factor",
     "legendFormat": "Limits"
    },
    {
     "expr": "(sum(kube_pod_container_resource_requests{job=\"gpu-metrics\", namespace=~\"$namespace\", resource=\"cpu\", container!='istio-proxy'} and on (pod) label_replace(notebook_info{exported_namespace=~\"$namespace\"}, \"pod\", \"$1\", \"exported_pod\", \"(.+)\") and on(pod) (kube_pod_status_phase{job=\"gpu-metrics\", namespace=~\"$namespace\",phase=\"Running\"} == 1)) or clamp_max(absent(kube_pod_container_resource_requests{job=\"gpu-metrics\", namespace=~\"$namespace\", resource=\"cpu\", container!='istio-proxy'} and on (pod) label_replace(notebook_info{exported_namespace=~\"$namespace\"}, \"pod\", \"$1\", \"exported_pod\", \"(.+)\") and on(pod) (kube_pod_status_phase{job=\"gpu-metrics\", namespace=~\"$namespace\",phase=\"Running\"} == 1)), 0))\n+\n(sum(kube_pod_container_resource_requests{job=\"gpu-metrics\", namespace=~\"$namespace\", resource=\"cpu\", container='tensorboard'} and on(pod) (kube_pod_status_phase{job=\"gpu-metrics\", namespace=~\"$namespace\",phase=\"Running\"} == 1)) or clamp_max(absent(kube_pod_container_resource_requests{job=\"gpu-metrics\", namespace=~\"$namespace\", resource=\"cpu\", container='tensorboard'} and on(pod) (kube_pod_status_phase{job=\"gpu-metrics\", namespace=~\"$namespace\",phase=\"Running\"} == 1)), 0))",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=~\"$namespace\", container!~\"istio.*\", container=~\".+\"} OR clamp_max(absent(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=~\"$namespace\", container!~\"istio.*\", container=~\".+\"}), 0))",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "GPU Quota",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "unit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_resourcequota{job=\"gpu-metrics\", namespace=~\"$namespace\", resource=\"requests.nvidia.com/gpu\", type=\"hard\"})",
     "legendFormat": "Limits"
    },
    {
     "expr": "sum(kube_resourcequota{job=\"gpu-metrics\", namespace=~\"$namespace\", resource=\"requests.nvidia.com/gpu\", type=\"used\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "count(DCGM_FI_DEV_GPU_UTIL{namespace=~\"$namespace\"} > 0) or clamp_max(absent(DCGM_FI_DEV_GPU_UTIL{namespace=~\"$namespace\"} > 0), 0)",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Memory Quota",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_resourcequota{job=\"gpu-metrics\", namespace=~\"$namespace\", resource=\"memory\", type=\"hard\"}) * 1/$buffer_factor",
     "legendFormat": "Limits"
    },
    {
     "expr": "(sum(kube_pod_container_resource_requests{job=\"gpu-metrics\", namespace=~\"$namespace\", resource=\"memory\", container!='istio-proxy'} and on (pod) label_replace(notebook_info{exported_namespace=~\"$namespace\"}, \"pod\", \"$1\", \"exported_pod\", \"(.+)\") and on(pod) (kube_pod_status_phase{job=\"gpu-metrics\", namespace=~\"$namespace\",phase=\"Running\"} == 1)) or clamp_max(absent(kube_pod_container_resource_requests{job=\"gpu-metrics\", namespace=~\"$namespace\", resource=\"memory\", container!='istio-proxy'} and on (pod) label_replace(notebook_info{exported_namespace=~\"$namespace\"}, \"pod\", \"$1\", \"exported_pod\", \"(.+)\") and on(pod) (kube_pod_status_phase{job=\"gpu-metrics\", namespace=~\"$namespace\",phase=\"Running\"} == 1)), 0))\n+\n(sum(kube_pod_container_resource_requests{job=\"gpu-metrics\", namespace=~\"$namespace\", resource=\"memory\", container='tensorboard'} and on(pod) (kube_pod_status_phase{job=\"gpu-metrics\", namespace=~\"$namespace\",phase=\"Running\"} == 1)) or clamp_max(absent(kube_pod_container_resource_requests{job=\"gpu-metrics\", namespace=~\"$namespace\", resource=\"memory\", container='tensorboard'} and on(pod) (kube_pod_status_phase{job=\"gpu-metrics\", namespace=~\"$namespace\",phase=\"Running\"} == 1)), 0))",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=~\"$namespace\", container!~\"istio.*\", service=\"kube-prometheus-stack-kubelet\"} OR clamp_max(absent(container_memory_working_set_bytes{namespace=~\"$namespace\", container!~\"istio.*\", service=\"kube-prometheus-stack-kubelet\"}), 0))",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Storage Quota",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_resourcequota{job=\"gpu-metrics\", namespace=~\"$namespace\", resource=\"requests.storage\", type=\"hard\"})",
     "legendFormat": "Limits"
    },
    {
     "expr": "sum(kube_resourcequota{job=\"gpu-metrics\", namespace=~\"$namespace\", resource=\"requests.storage\", type=\"used\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(label_replace(longhorn_volume_actual_size_bytes, \"persistentvolume\", \"$1\", \"volume\", \"(.+)\") * on(persistentvolume) group_left(name, claim_namespace) (kube_persistentvolume_claim_ref{job=\"gpu-metrics\", claim_namespace=~\"$namespace\"} and on(claim_namespace) label_replace(database_workspace_info, \"claim_namespace\", \"$1\", \"exported_namespace\", \"(.+)\"))) OR clamp_max(absent(label_replace(longhorn_volume_actual_size_bytes, \"persistentvolume\", \"$1\", \"volume\", \"(.+)\") * on(persistentvolume) group_left(name, claim_namespace) (kube_persistentvolume_claim_ref{job=\"gpu-metrics\", claim_namespace=~\"$namespace\"} and on(claim_namespace) label_replace(database_workspace_info, \"claim_namespace\", \"$1\", \"exported_namespace\", \"(.+)\"))), 0)",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "GPU Status",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(label_replace(notebook_info * on(exported_namespace) group_left(workspace) database_workspace_info, \"namespace\", \"$1\", \"exported_namespace\", \"(.+)\")) by (namespace, workspace, notebook)"
    },
    {
     "expr": "sum(label_replace(DCGM_FI_DEV_GPU_UTIL{kubernetes_node=~\"$node\", namespace=~\"$namespace\"}, \"notebook\", \"$1\", \"container\", \"(.+)\")) by(UUID, kubernetes_node, gpu, modelName, namespace, notebook)"
    },
    {
     "expr": "sum(label_replace(DCGM_FI_DEV_MEM_COPY_UTIL{kubernetes_node=~\"$node\", namespace=~\"$namespace\"}, \"notebook\", \"$1\", \"container\", \"(.+)\")) by(UUID, kubernetes_node, gpu, modelName, namespace, notebook)"
    },
    {
     "expr": "sum(label_replace(DCGM_FI_DEV_FB_USED{kubernetes_node=~\"$node\", namespace=~\"$namespace\"} / (DCGM_FI_DEV_FB_FREE{kubernetes_node=~\"$node\", namespace=~\"$namespace\"} + DCGM_FI_DEV_FB_USED{kubernetes_node=~\"$node\", namespace=~\"$namespace\"}) * 100, \"notebook\", \"$1\", \"container\", \"(.+)\")) by(UUID, kubernetes_node, gpu, modelName, namespace, notebook)"
    },
    {
     "expr": "sum(label_replace(DCGM_FI_DEV_GPU_TEMP{kubernetes_node=~\"$node\", namespace=~\"$namespace\"}, \"notebook\", \"$1\", \"container\", \"(.+)\")) by(UUID, kubernetes_node, gpu, modelName, namespace, notebook)"
    },
    {
     "expr": "sum(label_replace(DCGM_FI_DEV_POWER_USAGE{kubernetes_node=~\"$node\", namespace=~\"$namespace\"}, \"notebook\", \"$1\", \"container\", \"(.+)\")) by(UUID, kubernetes_node, gpu, modelName, namespace, notebook)"
    }
   ]
  },
  {
   "title": "Notebook Status",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "label_replace(label_replace(label_replace((label_replace(label_replace(notebook_info{exported_namespace=~\"$namespace\"}, \"pod\", \"$1\", \"exported_pod\", \"(.+)\"), \"namespace\", \"$1\", \"exported_namespace\", \"(.+)\") * on (namespace, pod) group_left(Status) (label_replace(label_replace(label_replace(label_replace(label_replace(kube_pod_status_phase{job=\"gpu-metrics\", namespace=~\"$namespace\"}, \"Status\", \"0\", \"phase\", \"Failed\"), \"Status\", \"1\", \"phase\", \"Running\"), \"Status\", \"2\", \"phase\", \"Pending\"), \"Status\", \"3\", \"phase\", \"Succeeded\"), \"Status\", \"4\", \"phase\", \"Unknown\") == 1)) * on(exported_namespace) group_left(name) database_workspace_info{exported_namespace=~\"$namespace\"}, \"namespace\", \"$1\", \"exported_namespace\", \"(.+)\"), \"pod\", \"$1\", \"exported_pod\", \"(.+)\"), \"workspace\", \"$1\", \"name\", \"(.+)\")"
    },
    {
     "expr": "label_replace(label_replace(label_replace(label_replace(notebook_info{exported_namespace=~\"$namespace\"}, \"pod\", \"$1\", \"exported_pod\", \"(.+)\") * on(exported_namespace) group_left(name) database_workspace_info{exported_namespace=~\"$namespace\"}, \"namespace\", \"$1\", \"exported_namespace\", \"(.+)\"), \"pod\", \"$1\", \"exported_pod\", \"(.+)\"), \"workspace\", \"$1\", \"name\", \"(.+)\")"
    },
    {
     "expr": "(sum(label_replace(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=~\"$namespace\", container=~\".+\"}, \"notebook\", \"$1\", \"container\", \"(.+)\") and on(notebook) notebook_info{exported_namespace=~\"$namespace\"}) by (namespace, notebook) / sum(label_replace(kube_pod_container_resource_limits{job=\"gpu-metrics\", namespace=~\"$namespace\", resource=\"cpu\", container=~\".+\"}, \"notebook\", \"$1\", \"container\", \"(.+)\") and on(notebook) notebook_info{exported_namespace=~\"$namespace\"}) by (namespace, notebook)) and on(namespace) label_replace(database_workspace_info, \"namespace\", \"$1\", \"exported_namespace\", \"(.+)\")"
    },
    {
     "expr": "count(label_replace(DCGM_FI_DEV_GPU_UTIL >= 0, \"notebook\", \"$1\", \"container\", \"(.+)\") and on(notebook) notebook_info{exported_namespace=~\"$namespace\"} and on (namespace) label_replace(database_workspace_info{exported_namespace=~\"$namespace\"}, \"namespace\", \"$1\", \"exported_namespace\", \"(.+)\")) by (namespace, notebook)"
    },
    {
     "expr": "count(label_replace(DCGM_FI_DEV_GPU_UTIL == 0, \"notebook\", \"$1\", \"container\", \"(.+)\") and on(notebook) notebook_info{exported_namespace=~\"$namespace\"} and on (namespace) label_replace(database_workspace_info{exported_namespace=~\"$namespace\"}, \"namespace\", \"$1\", \"exported_namespace\", \"(.+)\")) by (namespace, notebook)"
    },
    {
     "expr": "(sum(label_replace(container_memory_working_set_bytes{namespace=~\"$namespace\", service=\"kube-prometheus-stack-kubelet\"}, \"notebook\", \"$1\", \"container\", \"(.+)\") and on(notebook) notebook_info{exported_namespace=~\"$namespace\"}) by (namespace, notebook) / sum(label_replace(kube_pod_container_resource_limits{job=\"gpu-metrics\", namespace=~\"$namespace\", resource=\"memory\", container=~\".+\"}, \"notebook\", \"$1\", \"container\", \"(.+)\") and on(notebook) notebook_info{exported_namespace=~\"$namespace\"}) by (namespace, notebook)) and on(namespace) label_replace(database_workspace_info, \"namespace\", \"$1\", \"exported_namespace\", \"(.+)\")"
    },
    {
     "expr": "sum(notebook_info{persistentvolumeclaim!=\"NONE\"} and on (exported_namespace) database_workspace_info{exported_namespace=~\"$namespace\"}) by (notebook)"
    },
    {
     "expr": "sum(label_replace(database_workspace_info{exported_namespace=~\"$namespace\"} and on(exported_namespace) notebook_info{exported_namespace=~\"$namespace\"}, \"namespace\", \"$1\", \"exported_namespace\", \"(.+)\")) by (namespace, workspace)"
    }
   ]
  },
  {
   "title": "Volume Status",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "label_replace(label_replace(label_replace(label_replace(label_replace(label_replace(label_replace(label_replace(storage_volume_info, \"State\", \"1\", \"state\", \"attached\"), \"State\", \"0\", \"state\", \"detached\"), \"Status\", \"1\", \"pvStatus\", \"Available\"), \"Status\", \"2\", \"pvStatus\", \"Bound\"), \"Status\", \"3\", \"pvStatus\", \"Released\"), \"Status\", \"0\", \"pvStatus\", \"Fail\"), \"Robustness\", \"1\", \"robustness\", \"healthy\"), \"Robustness\", \"0\", \"robustness\", \"unknown\") * on (persistentvolume) group_left (claim_namespace) label_replace(kube_persistentvolume_claim_ref{job=\"gpu-metrics\", claim_namespace=~\"$namespace\"}, \"persistentvolumeclaim\", \"$1\", \"name\", \"(.+)\")"
    },
    {
     "expr": "sum(label_replace(label_replace(longhorn_volume_actual_size_bytes, \"persistentvolume\", \"$1\", \"volume\", \"(.+)\") * on(persistentvolume) group_left(name, claim_namespace) kube_persistentvolume_claim_ref{job=\"gpu-metrics\", claim_namespace=~\"$namespace\"} and on (persistentvolume) kube_persistentvolume_info{job=\"gpu-metrics\", storageclass=~\"longhorn|longhorn-static\"}, \"persistentvolumeclaim\", \"$1\", \"name\", \"(.+)\")) by (persistentvolume, persistentvolumeclaim)\n/\nsum(kube_persistentvolume_capacity_bytes{job=\"gpu-metrics\"} * on (persistentvolume) group_left(namespace, persistentvolumeclaim) label_replace(kube_persistentvolumeclaim_info{job=\"gpu-metrics\", namespace=~\"$namespace\"}, \"persistentvolume\", \"$1\", \"volumename\", \"(.+)\")) by (persistentvolume, persistentvolumeclaim)"
    }
   ]
  }
 ]
}
{
 "title": "Workspace Card",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": "select concat('ns-', id) as namespace\nfrom haiqv_workspace"
   },
   { "name": "buffer_factor", "query": "1.1" }
  ]
 },
 "panels": [
  {
   "type": "table",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "label_replace(sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=~\"$namespace\", container!~\"istio.*\", container=~\".+\"} OR clamp_max(absent(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=~\"$namespace\",  container!~\"istio.*\", container=~\".+\"}), 0))\n / (sum(kube_resourcequota{job=\"gpu-metrics\", namespace=~\"$namespace\", resource=\"cpu\", type=\"hard\"} > 0) * 1/$buffer_factor) * 100, \"Resource\", \"CPU\", \"\", \"\")"
    },
    {
     "expr": "label_replace((((count(DCGM_FI_DEV_GPU_UTIL{namespace=~\"$namespace\"} > 0) or clamp_max(absent(DCGM_FI_DEV_GPU_UTIL{namespace=~\"$namespace\"} > 0), 0)) / sum(kube_resourcequota{job=\"gpu-metrics\", namespace=~\"$namespace\", resource=\"requests.nvidia.com/gpu\", type=\"hard\"} > 0))) * 100 or clamp_max(absent(sum(kube_resourcequota{job=\"gpu-metrics\", namespace=~\"$namespace\", resource=\"requests.nvidia.com/gpu\", type=\"hard\"} > 0)), -1), \"Resource\", \"GPU\", \"\", \"\")"
    },
    {
     "expr": "label_replace(sum(container_memory_working_set_bytes{namespace=~\"$namespace\", container!~\"istio.*\", service=\"kube-prometheus-stack-kubelet\"} OR clamp_max(absent(container_memory_working_set_bytes{namespace=~\"$namespace\", container!~\"istio.*\", service=\"kube-prometheus-stack-kubelet\"}), 0)) / (sum(kube_resourcequota{job=\"gpu-metrics\", namespace=~\"$namespace\", resource=\"memory\", type=\"hard\"} > 0) * 1/$buffer_factor) * 100, \"Resource\", \"Memory\", \"\", \"\")"
    },
    {
     "expr": "label_replace((sum(label_replace(longhorn_volume_actual_size_bytes, \"persistentvolume\", \"$1\", \"volume\", \"(.+)\") * on(persistentvolume) group_left(name, claim_namespace) kube_persistentvolume_claim_ref{job=\"gpu-metrics\", claim_namespace=~\"$namespace\"}) OR clamp_max(absent(label_replace(longhorn_volume_actual_size_bytes, \"persistentvolume\", \"$1\", \"volume\", \"(.+)\") * on(persistentvolume) group_left(name, claim_namespace) kube_persistentvolume_claim_ref{job=\"gpu-metrics\", claim_namespace=~\"$namespace\"}), 0)) / sum(kube_resourcequota{job=\"gpu-metrics\", namespace=~\"$namespace\", resource=\"requests.storage\", type=\"hard\"} > 0) * 100, \"Resource\", \"Storage\", \"\", \"\")"
    }
   ]
  }
 ]
}